function generateStatement() {

    document.getElementById("sTransactionId").innerText = document.getElementById("transactionId").value;

    document.getElementById("sAmount").innerText = document.getElementById("amount").value;

    document.getElementById("sGame").innerText = document.getElementById("game").value;

    document.getElementById("sPaymentMethod").innerText = document.getElementById("paymentMethod").value;

    document.getElementById("sTransactionTime").innerText = document.getElementById("transactionTime").value;

    let extraText = document.getElementById("extraText").value;

    document.getElementById("sExtraText").innerText = extraText ? `"${extraText}"` : "";

    document.getElementById("statement").style.display = "block";

}

function downloadImage() {

    let statementElement = document.getElementById("statement");

    html2canvas(statementElement, { scale: 3 }).then(canvas => {

        let ctx = canvas.getContext("2d");

        // **Adding Watermark**

        ctx.font = "20px Arial";

        ctx.fillStyle = "rgba(0, 0, 0, 0.5)";

        ctx.textAlign = "right";

        ctx.fillText("© Copyright Kiran Official", canvas.width - 20, canvas.height - 20);

        let link = document.createElement("a");

        link.download = "payment_statement.jpg";

        link.href = canvas.toDataURL("image/jpeg", 1.0);

        link.click();

        // **For Mobile Gallery Auto-Save**

        let blob = dataURLtoBlob(link.href);

        saveToGallery(blob);

    });

}

// **Convert Data URL to Blob**

function dataURLtoBlob(dataurl) {

    let arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1];

    let bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);

    while (n--) { u8arr[n] = bstr.charCodeAt(n); }

    return new Blob([u8arr], { type: mime });

}

// **Save Image to Gallery**

function saveToGallery(blob) {

    let file = new File([blob], "payment_statement.jpg", { type: "image/jpeg" });

    let formData = new FormData();

    formData.append("file", file);

    if (navigator.canShare && navigator.canShare({ files: [file] })) {

        navigator.share({

            files: [file],

            title: "Payment Statement",

            text: "Generated by Kiran Top Up Centre"

        });

    } else {

        alert("Download successful, but gallery save may require manual action.");

    }

}